"""Add report embedding vector

Revision ID: 47e81d4e4c8f
Revises: 5f928c58895b
Create Date: 2026-09-22 18:04:34.391518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '47e81d4e4c8f'
down_revision: Union[str, Sequence[str], None] = '5f928c58895b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('embedding', VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'embedding')
    # ### end Alembic commands ###
