"""Add AI classification fields

Revision ID: 5f928c58895b
Revises: 64e1b91d61dc
Create Date: 2026-09-21 18:18:08.328109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f928c58895b'
down_revision: Union[str, Sequence[str], None] = '64e1b91d61dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'reports',
        sa.Column(
            'category',
            sa.String(length=50),
            nullable=True
        )
    )

    op.add_column(
        'reports',
        sa.Column(
            'priority',
            sa.String(length=20),
            nullable=True
        )
    )

    op.add_column(
        'reports',
        sa.Column(
            'summary',
            sa.String(length=500),
            nullable=True
        )
    )

    # Backfill existing reports
    op.execute(
        "UPDATE reports SET category = 'Other' WHERE category IS NULL"
    )

    op.execute(
        "UPDATE reports SET priority = 'Medium' WHERE priority IS NULL"
    )

    op.execute(
        "UPDATE reports SET summary = description WHERE summary IS NULL"
    )

    # Make the columns required after existing rows are populated
    op.alter_column(
        'reports',
        'category',
        existing_type=sa.String(length=50),
        nullable=False
    )

    op.alter_column(
        'reports',
        'priority',
        existing_type=sa.String(length=20),
        nullable=False
    )

    op.alter_column(
        'reports',
        'summary',
        existing_type=sa.String(length=500),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'summary')
    op.drop_column('reports', 'priority')
    op.drop_column('reports', 'category')
    # ### end Alembic commands ###
