"""Add report severity

Revision ID: 64e1b91d61dc
Revises: 4ea58ba5048f
Create Date: 2026-09-19 10:11:19.355685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e1b91d61dc'
down_revision: Union[str, Sequence[str], None] = '4ea58ba5048f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'reports',
        sa.Column(
            'severity',
            sa.String(length=20),
            nullable=True
        )
    )

    op.execute(
        "UPDATE reports SET severity = 'MEDIUM' WHERE severity IS NULL"
    )

    op.alter_column(
        'reports',
        'severity',
        existing_type=sa.String(length=20),
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'severity')
    # ### end Alembic commands ###
