"""Add latitude and longitude to reports

Revision ID: 998527151b56
Revises: 47e81d4e4c8f
Create Date: 2026-09-23 12:21:44.117410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998527151b56'
down_revision: Union[str, Sequence[str], None] = '47e81d4e4c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'longitude')
    op.drop_column('reports', 'latitude')
    # ### end Alembic commands ###
