"""add_department_head_fields

Revision ID: ef82e52d043f
Revises: e4c81619df3e
Create Date: 2026-09-23 18:05:13.917190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef82e52d043f'
down_revision: Union[str, Sequence[str], None] = 'e4c81619df3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('assigned_to', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('remarks', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'remarks')
    op.drop_column('incidents', 'assigned_to')
    # ### end Alembic commands ###
